### ISSUE TITLE
Add integration/acceptance/smoke test to GHA

### ISSUE THREAD

**Issue by tboeghk** [observabilitystack/geoip-api#137]
I'd like to have a GHA script that checks out the current `latest` image and requests some known ip addresses for a sanity check. We should use `bats` for the job.

```yaml
name: daily integration test
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 5 * * *'
jobs:
  acceptance-test:
    runs-on: ubuntu-latest

    services:
      geoip-api:
        image: ghcr.io/${{ github.repository }}:latest
        ports:
          - 8080:8080

    steps:
      - uses: actions/checkout@v3
```
